Gp1/formblock
SergSch/tel-ran-project pull request #9
Opened 2024-03-26 09:57 UTC by olena-star

check please new changes

2024-03-27 14:28 UTC, OlenaMykhaylenko commented
Check please new changes

2024-03-27 20:33 UTC, SergSch requested changes
Опять удален с общих стилей контейнер, ну и FormBlock вставлен в App.js, он должен быть не там.

2024-04-10 13:14 UTC, OlenaMykhaylenko commented
Yes i am understant

2024-04-12 10:43 UTC, OlenaMykhaylenko reviewed
i wiil make changes

2024-04-12 10:44 UTC, OlenaMykhaylenko commented
it is good working

2024-04-16 12:23 UTC, closed without merging

2024-04-16 12:23 UTC, OlenaMykhaylenko commented
i will make changes